//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizeUlasin
    {
        public int mesajId { get; set; }
        public string mesajAd { get; set; }
        public string mesajEmail { get; set; }
        public string mesajTelefon { get; set; }
        public string mesajDetay { get; set; }
        public string mesajTarih { get; set; }
    }
}
