//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CocukYorum
    {
        public int cocukYorumId { get; set; }
        public string cocukAd { get; set; }
        public string cocukSoyad { get; set; }
        public string cocukFoto { get; set; }
        public string cocukOyuncakFoto { get; set; }
        public string cocukYorum1 { get; set; }
        public Nullable<int> cocukRutbeId { get; set; }
    
        public virtual CocukRutbe CocukRutbe { get; set; }
    }
}
