//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpostaYayınla
    {
        public int ePostaId { get; set; }
        public string ePostaKonu { get; set; }
        public string ePostaIcerik { get; set; }
        public string ePostaDosya { get; set; }
    }
}
