//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeriIade
    {
        public int geriIadeId { get; set; }
        public Nullable<int> geriIadesiparisId { get; set; }
        public string geriIadeSebep { get; set; }
        public string geriIadeTalep { get; set; }
    }
}
