//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanya
    {
        public int kampanyaId { get; set; }
        public Nullable<int> kampanyaTurId { get; set; }
        public Nullable<int> kampanyaIndirimOran { get; set; }
        public Nullable<System.DateTime> kampanyaBaslangicTarih { get; set; }
        public Nullable<System.DateTime> kampanyabitisTarih { get; set; }
        public Nullable<int> kampanyaTipId { get; set; }
        public string kampanyaTip { get; set; }
    
        public virtual KampanyaTur KampanyaTur { get; set; }
    }
}
