//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciDetay
    {
        public Nullable<int> sehirId { get; set; }
        public Nullable<int> ulkeId { get; set; }
        public Nullable<bool> kullaniciCinsiyet { get; set; }
        public int kullaniciId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual Ulkeler Ulkeler { get; set; }
    }
}
