//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeDetay
    {
        public int siparisId { get; set; }
        public int odemeTipiId { get; set; }
        public string kartUzerindekiAd { get; set; }
        public string kartUzerindekiNo { get; set; }
        public string ayYıl { get; set; }
    
        public virtual OdemeTipi OdemeTipi { get; set; }
        public virtual Siparis Siparis { get; set; }
    }
}
