//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SifreSifirla
    {
        public int sifreId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public Nullable<System.Guid> sifre { get; set; }
        public Nullable<System.DateTime> guncellenmeTarih { get; set; }
        public string eskiSifre { get; set; }
    }
}
