//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.OdemeDetay = new HashSet<OdemeDetay>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int siparisId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public Nullable<decimal> toplamFiyat { get; set; }
        public Nullable<bool> sepetteMi { get; set; }
        public Nullable<int> kargoId { get; set; }
        public Nullable<int> siparisDurumId { get; set; }
        public Nullable<int> odemeTipiId { get; set; }
        public Nullable<System.DateTime> siparisTarih { get; set; }
        public Nullable<System.DateTime> SiparisTeslimTarih { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdemeDetay> OdemeDetay { get; set; }
        public virtual OdemeTipi OdemeTipi { get; set; }
        public virtual SiparisDurum SiparisDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
