//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Puan = new HashSet<Puan>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.UrunResim = new HashSet<UrunResim>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int urunId { get; set; }
        public Nullable<int> altKategoriId { get; set; }
        public Nullable<int> markaId { get; set; }
        public string urunAd { get; set; }
        public string urunTanim { get; set; }
        public Nullable<int> urunFiyat { get; set; }
        public Nullable<bool> urunAktifMi { get; set; }
        public Nullable<int> urunStokSayisi { get; set; }
        public string urunRenk { get; set; }
        public string urunBoyut { get; set; }
        public string urunEklenmeTarih { get; set; }
        public Nullable<int> urunYas { get; set; }
        public string urunTekResim { get; set; }
        public Nullable<bool> urunKampanyaVarMı { get; set; }
        public Nullable<int> urunEskiFiyat { get; set; }
    
        public virtual AltKategori AltKategori { get; set; }
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puan> Puan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunResim> UrunResim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
